[[commands]]
name = "update-emacs-webrender"
category = "Update"
command = "nix flake lock --update-input emacsWebrenderSource"
help = "update EmacsWebrender src"

[[commands]]
name = "update-rustOverlay"
category = "Update"
command = "nix flake lock --update-input rust-overlay"
help = "update rust overlay"

[[commands]]
name = "update-nixpkgs"
category = "Update"
command = "nix flake lock --update-input nixpkgs"
help = "update nixpkgs channel"

[[commands]]
name = "update-master"
category = "Update"
command = "nix flake lock --update-input master"
help = "update nixpkgs of master channel"

[[commands]]
name = "emacs"
command = '''
        $(nix-build . --option substituters "https://cache.nixos.org https://emacs-webrender.cachix.org")/bin/emacs $@
        '''
help = "launch emacs-webrender"
category = "emacsWebrender"

[[commands]]
name = "cachix-push"
category = "update"
command = "nix-build | cachix push emacs-webrender"
help = "nix-build localy then push to cachix"

[[commands]]
name = "lock"
category = "develop"
command = '''
        sed -i 's|\#emacsWebrenderSource = emacs|emacsWebrenderSource = emacs|' flake.nix
        nix flake lock --update-input emacsWebrender-source
        '''
help = "lock rev for bindary cache build"

[[commands]]
name = "develop"
category = "emacsWebrender"
command = '''
        sed -i 's|git+https://github.com/emacs-ng/emacs-ng?submodule=1|path:./.|' flake.nix
        nix flake lock --update-input emacsWebrender-source
        '''
help = "using src = ./. for develop mode"
# [[env]]
# name = "HOME"
# value = "bin/test"
