---
# Requires _prepare.yml and _build.yml re-usable workflows to have run.
name: _release
on:
  workflow_call:
    inputs:
      plan_artifact:
        description: Name of artifact containing a emacs-builder plan yaml file
        type: string
        required: true
      tbz_artifact:
        description: Name of artifact containing a *.dmg files to release
        type: string
        required: true
    secrets:
      TAP_REPO_TOKEN:
        description: Personal Access Token for Homebrew Tap repo
        required: true

jobs:
  github:
    runs-on: macos-11
    steps:
      - name: Download pre-built emacs-builder artifact
        uses: actions/download-artifact@v3
        with:
          name: emacs-builder
          path: bin
      - name: Ensure emacs-builder is executable
        run: chmod +x bin/emacs-builder
      - name: Download build-plan.yml artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.plan_artifact }}
          path: ./
      - name: Download disk image artifacts
        id: dmg
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tbz_artifact }}
          path: builds
      - name: Publish tbz archive to a GitHub Release
        if: ${{ steps.dmg.outputs.result != 'fail' }}
        run: >-
          bin/emacs-builder -l debug release --plan build-plan.yml publish
          $(find builds -name '*.tbz')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
